### ISSUE TITLE
화면 설계

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip-flask#1]
화면 설계하기

**Comment by 97kim** [comment]
<img width="678" alt="스크린샷 2021-09-23 오후 9 12 33" src="https://user-images.githubusercontent.com/64389162/134518192-26eec13a-c927-47f3-ab49-92265609762c.png">

**Comment by hyojin-dev** [comment]
확인했습니다!

**Comment by shinsiwoo2108** [comment]
확인완료

**Comment by woogys** [comment]
넵 이대로 가면 좋을 것 같습니다. 확인했습니다!
