### ISSUE TITLE
API 설계

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip-flask#2]
API 설계하기

**Comment by 97kim** [comment]
<img width="766" alt="스크린샷 2021-09-23 오후 10 48 55" src="https://user-images.githubusercontent.com/64389162/134519117-4f3cdb83-23f1-4a2c-b09e-0b4fd04b2744.png">

**Comment by hyojin-dev** [comment]
확인했습니다!

**Comment by shinsiwoo2108** [comment]
확인완료

**Comment by woogys** [comment]
확인했습니다.

**Comment by 97kim** [comment]
변경
<img width="818" alt="스크린샷 2021-09-24 오후 12 29 24" src="https://user-images.githubusercontent.com/64389162/134613775-22bf6392-cfc1-435b-9575-e29b4d4a7a79.png">
