### ISSUE TITLE
open API 사용

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip-flask#3]
[https://www.data.go.kr/iim/api/selectAPIAcountView.do](url)에서 사용에 문제 없는지 확인하기

**Comment by 97kim** [comment]
한국 관광 공사에서 api 활용 신청 명단에 제가 안 올라왔다고 하네요. 조금만 더 기다려보고 명단에 계속 올라오지 않으면 다시 연락준다고 합니다.

**Comment by woogys** [comment]
저도 안 됐었는데 이제 사용 가능해 졌어요!

**Comment by 97kim** [comment]
-해결 완료-
