### ISSUE TITLE
2차 프로젝트 기능 추가 사항

### ISSUE THREAD

**Issue by 97kim** [97kim/mytrip-flask#56]
첫 화면 생성
회원가입 / 로그인 기능
추천 여행지 기능
근처 여행지 리스트 / 리뷰 리스트
근처 여행지 상세페이지 / 리뷰 상세페이지
날씨
프로필 사진 추가
공유하기
좋아요 / 즐겨찾기
댓글
AWS S3 / 자동 배포

**Comment by woogys** [comment]
좋아요 / 즐겨찾기 !

**Comment by hyojin-dev** [comment]
회원가입 / 로그인 기능 !

**Comment by 97kim** [comment]
근처 여행지 상세페이지 / 리뷰 상세페이지 !
